# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build with Maven

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        java-version: [ 11, 16 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up multi JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml     
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
          name: test-results-${{ matrix.java-version }}
          path: target/surefire-reports
   
  publish:
    runs-on: ubuntu-latest 
    needs: build
    strategy:
      matrix:
        java-version: [ 11, 16 ]
    steps:  
     - name: Download Artifacts
       uses: actions/download-artifact@v2.0.10
       with:
        name: test-results-${{ matrix.java-version }}
        path: ./
     - name: Publish Unit Test Results
       uses: EnricoMi/publish-unit-test-result-action@v1.23
       if: always()
       with:
          check_name: Unit Test Results
          files: 'target/surefire-reports/*.xml'
