name: 'Test Report'
on:
  workflow_run:
    workflows: ['Build with Maven']                     # runs after CI workflow
    types:
      - completed
   
jobs:
  publish-test-results:
    name: "Publish Test Results"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 16 ]
    steps:
      - name: Download Test Artifacts
        uses: dawidd6/action-download-artifact@v2.15.0
        with:
          workflow: maven.yml
          workflow_conclusion: success
          name: test-results-${{ matrix.java-version }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.23
        if: always()
        with:
          check_name: Unit Test Results
          files: '**/*.xml'
